language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pk/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-837154701587"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY